# Generated by Django 5.0.6 on 2024-05-28 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fenjan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='registeration_state',
            new_name='registration_state',
        ),
    ]
