# Generated by Django 5.0.6 on 2024-06-23 19:26

import fenjan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fenjan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='expiration_date',
            field=models.DateField(default=fenjan.models.default_expiration_date),
        ),
    ]
