# Generated by Django 5.1.6 on 2025-03-17 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fenjan', '0003_linkedinsearchresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedinsearchresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fenjan.customer'),
        ),
    ]
