# Generated by Django 5.1.6 on 2025-04-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fenjan', '0004_alter_linkedinsearchresult_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinsearchresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
