# Generated by Django 5.1.6 on 2025-04-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fenjan', '0005_linkedinsearchresult_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedinsearchresult',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
