# Generated by Django 5.1.6 on 2025-04-13 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fenjan', '0006_alter_linkedinsearchresult_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='registration_date',
            field=models.DateField(default=datetime.date(2025, 4, 13)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
